name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # This pattern matches tags with three numeric parts separated by dots.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish

